deployment:
  tasks:
    - export DEPLOYPATH=/home/u650263172/domains/guitarclassbynde.id/public_html
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:clear
    - cd $DEPLOYPATH && php artisan route:clear
    - cd $DEPLOYPATH && php artisan view:clear

